### ISSUE TITLE
List on Mailspring Community

### ISSUE THREAD

**Issue by CodeMouse92** [Striffly/mailspring-avatars#1]
We just launched the official [Mailspring Community](https://community.getmailspring.com), which among other things, has a dedicated place for listing plugins: https://community.getmailspring.com/c/plugins/8

Would you be willing to join that community and post a listing for this plugin there, to aid in discovery? Additionally, if you PM me, I can add you to the Plugin Developers group.

P.S. This plugin works perfectly on Mailspring 1.8.0! 😁 Loving it.

**Comment by tennox** [comment]
He has done it! https://community.getmailspring.com/c/plugins/8 :sunglasses:  :tada:
