### ISSUE TITLE
Issue when last name contains brackets

### ISSUE THREAD

**Issue by 1RandomDev** [Striffly/mailspring-avatars#11]
I noticed that on some notification mails which have round brackets in the last name for example `C... T... (über mebis)` the icon looks like this: 
![Bildschirmfoto vom 2023-03-09 14-52-43](https://user-images.githubusercontent.com/84292805/224046166-ad076f2c-9b09-4825-b563-2f06b8465785.png)

**Comment by 1RandomDev** [comment]
Also for `G... J... via Mailspring Community <hello@getmailspring.com>` the text is longer than the circle. Would it be possible to limit the number of characters to 3?

**Comment by Striffly** [comment]
Done ! See release 1.4.0 : https://github.com/Striffly/mailspring-avatars/releases/tag/1.4.0
