### ISSUE TITLE
Different Color for same sender Adress

### ISSUE THREAD

**Issue by renky** [Striffly/mailspring-avatars#12]
I really like this plugin, because it gives me much more overview on the inbox... unfortunately there seems no rule about the colorizing of initials if there is no avatar...

I received 3 mails from the same person and got 3 different images with different colors - its missleading visualisation, because it looks like different senders:
<img width="57" alt="image" src="https://github.com/Striffly/mailspring-avatars/assets/6528960/661ac9ee-3c54-428d-9371-a45a60f560c1">

On Android FairMail they use also letter in the avatar images, but keep the color identical for each sender... it this also possible? maybe the plugin must also save hashes for the mail address and finally lookup if it already had a colorized image...

**Comment by Striffly** [comment]
Done ! See release 1.4.0 : https://github.com/Striffly/mailspring-avatars/releases/tag/1.4.0
