### ISSUE TITLE
Unread mark is hidden by avatar

### ISSUE THREAD

**Issue by Krit1960** [Striffly/mailspring-avatars#13]
After the plugin is installed the avatars show up. Great!
The only problem is that the unread mark isn't visible anymore, only when you hover the mouse over the avatar it will show.

Windows 11, latest updates installed

**Comment by Krit1960** [comment]
Sorry about that, this is not a problem of the plugin but it's the theme Taiga that messed things up.

**Comment by Krit1960** [comment]
Sorry about that, this is not a problem of the plugin but it's the theme Taiga that messed things up.

**Comment by Striffly** [comment]
Haha, glad your problem is solved!
