### ISSUE TITLE
Doesn't load on Mailspring installed with yay on Arch Linux

### ISSUE THREAD

**Issue by Dark-Witcher** [Striffly/mailspring-avatars#15]
Hello,

I am getting the following error in the console:

`node:internal/modules/cjs/loader:1154 Uncaught Error: Cannot find module '/home/$USER/.config/Mailspring/packages/mailspring-avatars/lib/main'
Require stack:
- /opt/mailspring/resources/app.asar/src/package.js
- /opt/mailspring/resources/app.asar/src/package-manager.js
- /opt/mailspring/resources/app.asar/src/app-env.js
- /opt/mailspring/resources/app.asar/src/window-bootstrap.js
- /opt/mailspring/resources/app.asar/static/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1151:15)
    at Function.a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:992:27)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Package.activate (/tmp/nylas-build/electron-packager/tmp-tqt57s/resources/app/src/package.ts:46:22)
    at PackageManager.activatePackage (/tmp/nylas-build/electron-packager/tmp-tqt57s/resources/app/src/package-manager.ts:129:9)
    at /tmp/nylas-build/electron-packager/tmp-tqt57s/resources/app/src/package-manager.ts:92:14`

I checked the Mailspring folder in /opt but it doesn't contain any of these, besides package.js in /opt/mailspring/resources/app.asar.unpacked/node_modules/windows-shortcuts.

This is on the latest version of Mailspring. It works fine in Windows.

**Comment by Striffly** [comment]
Hmm, this is strange. Mailspring is supposed to install the plugin on this folder.

Did you use the zip file from my latest release for the installation? How did you install the plugin?

**Comment by Dark-Witcher** [comment]
I downloaded the latest release of the plug in as a zip file from the repo, the extracted it and installed it by using the installer in Mailspring developer tab.

**Comment by Striffly** [comment]
That seems fine, though.
I also use Arch (btw), and I follow the same installation process for both Mailspring and the plugin.
Could you try deleting this folder and then reinstalling the plugin: `/home/$USER/.config/Mailspring/packages/mailspring-avatars/` ?

**Comment by Dark-Witcher** [comment]
Just downloaded the latest version, that you have released 2 days ago and installed it and it works. But while checking the console I saw this:

![Screenshot From 2024-10-26 22-36-05](https://github.com/user-attachments/assets/70ef8615-087a-440e-a12b-7b984d7ea20d)

**Comment by Striffly** [comment]
Yes it's a known issue; I talked about it here: https://community.getmailspring.com/t/mailspring-avatars/989/30

I'm closing this issue.
