### ISSUE TITLE
Duplicate images in avatars

### ISSUE THREAD

**Issue by ghost** [Striffly/mailspring-avatars#2]
I installed the mailspring-avatars plugin. It works, but displays two different images for each avatar. MacOS Monterey beta 3

[Screenshot](https://www.icloud.com/iclouddrive/03NIOg50ek_wecGXs5plXeSxA#Screen_Shot_2021-07-20_at_11.59.57_PM)

**Comment by Akiracr** [comment]
I have the same issue on Linux

**Comment by Mestima** [comment]
Same on Windows 11

**Comment by forever-possessed** [comment]
Same issue on MacOs 10.14.6
Some also [appear broken](https://imgur.com/tZ7XewT)

**Comment by eyaskd** [comment]
how can I remove this plugin?

**Comment by tennox** [comment]
@eyaskd  LMGTFY...
-> https://github.com/Foundry376/Mailspring/issues/649

**Comment by eyaskd** [comment]
> @eyaskd LMGTFY... "mailspring uninstall plugin" -> [Foundry376/Mailspring#649](https://github.com/Foundry376/Mailspring/issues/649)

I'm using windows 11

**Comment by Striffly** [comment]
Even after several reinstall (Linux only), I can't reproduce this issue guys sorry :confused: <br>
Maybe it's due to a Mailspring update, or a conflict with another plugin ? Did you try to reinstall the plugin?

**Comment by tennox** [comment]
I tried this plugin and saw it not working when installed via snap.
Installed mailspring via deb and now it (and this plugin) seem to work well :)
:+1:

**Comment by andybrice** [comment]
> Even after several reinstall (Linux only), I can't reproduce this issue guys sorry 😕

I'm also experiencing this bug. Here are some screenshots and the HTML of an affected element, which may help diagnose the problem.

<img width="1204" alt="MailSpring Avatars Bug Duplicate Bug Screenshot 1" src="https://user-images.githubusercontent.com/106819/178949693-e16a7f3b-7860-4680-b74f-e32c7d7ff890.png">

<img width="1286" alt="MailSpring Avatars Bug Duplicate Bug Screenshot 2" src="https://user-images.githubusercontent.com/106819/178949699-35477cc0-936e-4ec3-8d96-eaa860f03762.png">

```html
<div data-item-id="t:v34Ff35NtNx3QnF5gHZXWB3yxXX1mX4pLJDS4iHJ"
  style="touch-action: pan-x pan-y; position: absolute; top: 0px; width: 100%; height: 85px;">
  <div class="swipe-backing" style="top: 0px; bottom: 0px; position: absolute;"></div>
  <div style="transform: translate3d(0px, 0px, 0px);">
    <div class="list-item list-tabular-item   " style="height: 85px;">
      <div class="list-column list-column-Item" style="flex: 1 1 0%;">
        <div style="display: flex; align-items: flex-start;">
          <div class="icons-column">
            <div class="thread-icon thread-icon-none thread-icon-star-on-hover" title="Star"></div>
            <div class="thread-injected-icons injected-region-visible"
              style="flex-direction: column; position: relative; display: inline-flex; height: 100%;"><span
                class="name"> role: ThreadListIcon (thread:&lt;Thread&gt;)</span>
              <div class="thread-avatar"
                style="display: inline-block; width: 32px; height: 32px; border-radius: 500px;"><img width="32"
                  height="32" src="http://logo.clearbit.com/InsideApple.Apple.com"
                  style="max-width: 100%; width: 32px; height: 32px; border-radius: 500px;"></div><span
                style="clear: both;"></span>
            </div>
          </div>
          <div class="thread-info-column">
            <div class="participants-wrapper">
              <div class="participants" dir="auto"><span></span><span class="unread-false">Apple</span></div><span
                style="flex: 1 1 0%;"></span>
              <div class="thread-injected-timestamp injected-region-visible"><span class="timestamp">Jun 24</span><span
                  class="name"> role: ThreadListTimestamp (thread:&lt;Thread&gt;, fallback:&lt;Function&gt;)</span><span
                  style="clear: both;"></span></div>
            </div>
            <div class="subject" dir="auto">Meet the new MacBook Pro 13”. Supercharged by M2.</div>
            <div class="snippet-and-labels">
              <div class="snippet" dir="auto">Do even more, even faster with the new MacBook Pro 13”. Available now. &zwnj; &zwnj;
                &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;
                &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;
                &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;
                &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;&nbsp;</div>
              <div style="flex: 1 1 0%;"></div>
              <div class="thread-injected-mail-labels injected-region-visible"
                style="flex-direction: row; position: relative; display: inline-flex; height: 100%;"><span class="name">
                  role: Thread:MailLabel (thread:&lt;Thread&gt;, messages:&lt;undefined&gt;)</span>
                <div class="thread-avatar"
                  style="display: inline-block; width: 42px; height: 42px; border-radius: 500px;"><img width="42"
                    height="42" src="http://logo.clearbit.com/InsideApple.Apple.com"
                    style="max-width: 100%; width: 42px; height: 42px; border-radius: 500px;"></div><span
                  style="clear: both;"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by andybrice** [comment]
It appears to me that for each thread, there is first an incorrectly positioned, 32px avatar at:
```css
div.icons-column > div.thread-injected-icons.injected-region-visible > div.thread-avatar > img
```

And then there's a second, correctly positioned, 42px avatar at:
```css
div.thread-info-column > div.snippet-and-labels > div.thread-injected-mail-labels.injected-region-visible > div.thread-avatar > img
```
The two avatars have this different width and height specified in the attributes of the `img` element, and in the inline styles of the `img` and `div` elements. Other than that, the html of both avatars is repeated identically.

**Comment by andybrice** [comment]
I'm guessing that for some of us, MailSpring is displaying both of these simultaneously:

https://github.com/Striffly/mailspring-avatars/blob/43f03afeaed0d46740faa649c507d614a4c861b8/src/main.js#L10-L14

(For some unknown reason.)

**Comment by GEkuL** [comment]
> Even after several reinstall (Linux only), I can't reproduce this issue guys sorry confused Maybe it's due to a Mailspring update, or a conflict with another plugin ? Did you try to reinstall the plugin?

Hi, the trouble appear when you make 3 panel view and make the inbox window narrower.
At some point, one avatar becomes 2.

Could you fix the issue, since it still persists? ):

**Comment by Striffly** [comment]
Issue finally resolved ! Sorry for the long wait :grimacing:  <br>
Thanks also to all of you for your contributions which allowed me to progress in my debug! I was able to reproduce the bug with a little luck <br>

New release added : [https://github.com/Striffly/mailspring-avatars/releases/tag/1.3.0](https://github.com/Striffly/mailspring-avatars/releases/tag/1.3.0)
