### ISSUE TITLE
broken image (url does not exist)

### ISSUE THREAD

**Issue by avelino** [Striffly/mailspring-avatars#3]
![Screen Shot 2022-04-16 at 15 23 13](https://user-images.githubusercontent.com/31996/163686982-a153cf52-7172-4915-9ddd-377e6ab6401f.png)

**Comment by Striffly** [comment]
The image is retrieved from Gravatar, so this 404 problem must come from there.
After inspecting the image (`Developer -> Toggle developer Tools`), can you specify the URL used?

**Comment by avelino** [comment]
@Striffly is **clearbit**
http://logo.clearbit.com/melhorrastreio.com.br

Ideally you should have a default image if there is no image in gravatar or clearbit, as there is in gmail (and other email clients).
![Screen Shot 2022-04-16 at 15 39 29](https://user-images.githubusercontent.com/31996/163687409-7d4a7461-f80d-472c-a20e-6aa77eef2ee4.png)

**Comment by Striffly** [comment]
From what I see in source code plugin try (in this order) : 
- Facebook
- Google
- Skype
- Gravatar
- and at last Clearbit

If none of them works, it use initials of email sender **name**, like this : 
![image](https://user-images.githubusercontent.com/13284087/163687872-fe9a3f74-c1c2-4781-90f2-c74060191bfd.png)

On the other hand it's strange that clearbit returns a 404, while you are supposed to fallback to the auto-generated image
